gnb_id: 222
gnb_id_bit_length: 34
ran_node_name: srsgnb01
gnb_du_id: 0
cells:
- pci: 1
  dl_arfcn: 536020
- pci: 2
  dl_arfcn: 532020
qos: null
srbs: null
cu_cp:
  max_nof_dus: null
  max_nof_cu_ups: null
  max_nof_ues: null
  max_nof_drbs_per_ue: null
  inactivity_timer: 120
  pdu_session_setup_timeout: 3
  load_plugins: false
  amf:
    addr: null
    port: 38412
    bind_addr: 127.0.0.1
    bind_interface: auto
    sctp_rto_initial: 120
    sctp_rto_min: 120
    sctp_rto_max: 500
    sctp_initial_max_attempts: 3
    sctp_max_init_timeo: 500
    sctp_nodelay: false
    no_core: false
    supported_tracking_areas:
    - tac: 7
      plmn_list:
      - plmn: '00101'
        tai_slice_support_list:
        - sst: 1
          sd: null
  mobility:
    trigger_handover_from_measurements: false
    cells:
    - nr_cell_id: null
      periodic_report_cfg_id: null
      ncells:
        nr_cell_id: null
        report_configs: null
      gnb_id: null
      ssb_arfcn: null
      band: null
      ssb_scs: null
      ssb_period: null
      ssb_offset: null
      ssb_duration: null
    report_configs:
    - report_cfg_id: null
      report_type: null
      report_interval_ms: 1024
      a3_report_type: null
      a3_offset_db: null
      a3_hysteresis_db: null
      a3_time_to_trigger_ms: null
  rrc:
    force_reestablishment_fallback: false
    rrc_procedure_timeout_ms: 720
  security:
    integrity: not_needed
    confidentiality: required
    nea_pref_list: nea0,nea2,nea1
    nia_pref_list: nia2,nia1
  f1ap:
    procedure_timeout: 1000
cu_up:
  gtpu_queue_size: 2048
  gtpu_reordering_timer: 0
  warn_on_drop: false
  upf:
    bind_addr: auto
    bind_interface: auto
    ext_addr: auto
    udp_max_rx_msgs: 256
    pool_threshold: 0.9
    no_core: false
du:
  warn_on_drop: false
cell_cfg:
  pci: 1
  sector_id: 0
  dl_arfcn: 536020
  band: auto
  common_scs: 15
  channel_bandwidth_MHz: 20
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  plmn: 65
  tac: 7
  q_rx_lev_min: -70
  q_qual_min: -20
  pcg_p_nr_fr1: 10
  slicing:
  - sst: 1
    sd: 0
    sched_cfg:
      min_prb_policy_ratio: 0
      max_prb_policy_ratio: 100
  mac_cell_group:
    bsr_cfg:
      periodic_bsr_timer: 10
      retx_bsr_timer: 80
      lc_sr_delay_timer: null
    phr_cfg:
      phr_prohibit_timer: 10
    sr_cfg:
      sr_trans_max: 64
      sr_prohibit_timer: null
  ssb:
    ssb_period: 10
    ssb_block_power_dbm: -16
    pss_to_sss_epre_db: 0
  sib:
    si_window_length: 160
    si_sched_info: null
    t300: 1000
    t301: 1000
    t310: 1000
    n310: 1
    t311: 3000
    n311: 1
    t319: 1000
  ul_common:
    p_max: null
    max_pucchs_per_slot: 31
    max_ul_grants_per_slot: 32
  pdcch:
    common:
      coreset0_index: null
      ss1_n_candidates:
        0: null
        1: null
      ss0_index: 0
      max_coreset0_duration: null
    dedicated:
      coreset1_rb_start: 1
      coreset1_l_crb: null
      coreset1_duration: null
      ss2_n_candidates:
        0: null
      dci_format_0_1_and_1_1: true
      ss2_type: ue_dedicated
  pdsch:
    min_ue_mcs: 0
    max_ue_mcs: 28
    fixed_rar_mcs: 0
    fixed_sib1_mcs: 5
    nof_harqs: 16
    max_nof_harq_retxs: 4
    max_consecutive_kos: 100
    rv_sequence:
    - 0
    - 2
    - 3
    - 1
    mcs_table: qam64
    min_rb_size: 1
    max_rb_size: 275
    start_rb: 0
    end_rb: 275
    max_pdschs_per_slot: 35
    max_alloc_attempts: 35
    olla_cqi_inc_step: 0.001
    olla_target_bler: 0.01
    olla_max_cqi_offset: 4
    dc_offset: null
    harq_la_cqi_drop_threshold: 3
    harq_la_ri_drop_threshold: 1
    dmrs_additional_position: 2
  pusch:
    min_ue_mcs: 0
    max_ue_mcs: 28
    max_consecutive_kos: 100
    rv_sequence:
    - 0
    mcs_table: qam64
    msg3_delta_preamble: 6
    p0_nominal_with_grant: -76
    msg3_delta_power: 8
    max_puschs_per_slot: 16
    b_offset_ack_idx_1: 9
    b_offset_ack_idx_2: 9
    b_offset_ack_idx_3: 9
    beta_offset_csi_p1_idx_1: 9
    beta_offset_csi_p1_idx_2: 9
    beta_offset_csi_p2_idx_1: 9
    beta_offset_csi_p2_idx_2: 9
    min_k2: 4
    dc_offset: null
    olla_snr_inc_step: 0.001
    olla_target_bler: 0.01
    olla_max_snr_offset: 5
    dmrs_additional_position: 2
    min_rb_size: 1
    max_rb_size: 275
    start_rb: 0
    end_rb: 275
    enable_transform_precoding: false
  pucch:
    p0_nominal: -90
    pucch_resource_common: 11
    sr_period_ms: 20
    use_format_0: false
    nof_ue_res_harq_per_set: 8
    f0_or_f1_nof_cell_res_sr: 8
    f0_intraslot_freq_hop: false
    f1_enable_occ: true
    f1_nof_cyclic_shifts: 2
    f1_intraslot_freq_hop: false
    nof_cell_harq_pucch_res_sets: 2
    f2_nof_cell_res_csi: 8
    f2_max_nof_rbs: 1
    f2_max_payload: null
    f2_max_code_rate: dot35
    f2_intraslot_freq_hop: false
    min_k1: 4
    max_consecutive_kos: 100
  srs:
    srs_period_ms: null
    srs_max_nof_sym_per_slot: 2
    srs_nof_sym_per_resource: 1
    srs_tx_comb: 4
    srs_cyclic_shift_reuse: 1
    srs_sequence_id_reuse: 1
  prach:
    prach_config_index: null
    prach_root_sequence_index: 1
    zero_correlation_zone: 0
    fixed_msg3_mcs: 0
    max_msg3_harq_retx: 4
    total_nof_ra_preambles: null
    prach_frequency_start: null
    preamble_rx_target_pw: -100
    preamble_trans_max: 7
    power_ramping_step_db: 4
    ports: null
    nof_ssb_per_ro: 1
    nof_cb_preambles_per_ssb: 4
    ra_resp_window: null
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10
    nof_dl_slots: 6
    nof_dl_symbols: 8
    nof_ul_slots: 3
    nof_ul_symbols: 0
    pattern2:
      dl_ul_tx_period: 10
      nof_dl_slots: 6
      nof_dl_symbols: 8
      nof_ul_slots: 3
      nof_ul_symbols: 0
  paging:
    pg_search_space_id: 1
    default_pg_cycle_in_rf: 128
    nof_pf_per_paging_cycle: oneT
    pf_offset: 0
    nof_po_per_pf: 1
  csi:
    csi_rs_enabled: true
    csi_rs_period: 20
    meas_csi_rs_slot_offset: null
    tracking_csi_rs_slot_offset: null
    zp_csi_rs_slot_offset: null
    pwr_ctrl_offset: 0
  sched_expert_cfg:
    policy_sched_cfg:
      pf_sched:
        pf_sched_fairness_coeff: 2
    ta_sched_cfg:
      ta_measurement_slot_period: 80
      ta_cmd_offset_threshold: 1
      ta_update_measurement_ul_sinr_threshold: 0
e2:
  enable_cu_e2: false
  enable_du_e2: false
  addr: 127.0.0.1
  port: 36421
  bind_addr: 127.0.0.1
  sctp_rto_initial: 120
  sctp_rto_min: 120
  sctp_rto_max: 500
  sctp_initial_max_attempts: 3
  sctp_max_init_timeo: 500
  e2sm_kpm_enabled: false
  e2sm_rc_enabled: false
ntn:
  cell_specific_koffset: 0
  ta_common: null
  epoch_time:
    sfn: 0
    subframe_number: 0
  ephemeris_info_ecef:
    pos_x: 0
    pos_y: 0
    pos_z: 0
    vel_x: 0
    vel_y: 0
    vel_z: 0
  ephemeris_orbital:
    semi_major_axis: 0
    eccentricity: 0
    periapsis: 0
    longitude: 0
    inclination: 0
    mean_anomaly: 0
ru_ofh:
  gps_alpha: 0
  gps_beta: 0
  ru_bandwidth_MHz: 0
  t1a_max_cp_dl: 500
  t1a_min_cp_dl: 258
  t1a_max_cp_ul: 500
  t1a_min_cp_ul: 258
  t1a_max_up: 300
  t1a_min_up: 85
  ta4_max: 300
  ta4_min: 85
  is_prach_cp_enabled: true
  is_dl_broadcast_enabled: false
  ignore_ecpri_seq_id: false
  ignore_ecpri_payload_size: false
  warn_unreceived_ru_frames: true
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_prach: bfp
  compr_bitwidth_prach: 9
  enable_ul_static_compr_hdr: true
  enable_dl_static_compr_hdr: true
  iq_scaling: 0.35
  cells:
  - network_interface: enp1s0f0
    ru_mac_address: 70:b3:d5:e1:5b:06
    du_mac_address: 00:11:22:33:00:77
    vlan_tag_cp: 1
    vlan_tag_up: 1
    ru_prach_port_id:
    - 4
    ru_dl_port_id:
    - 0
    - 1
    ru_ul_port_id:
    - 0
ru_sdr:
  srate: 61.44
  device_driver: uhd
  device_args: null
  tx_gain: 50
  rx_gain: 60
  freq_offset: 0
  clock_ppm: 0
  lo_offset: 0
  clock: default
  sync: default
  otw_format: default
  time_alignment_calibration: auto
  amplitude_control:
    tx_gain_backoff: 12.0
    enable_clipping: false
    ceiling: -0.1
  expert_cfg:
    low_phy_dl_throttling: 0
    tx_mode: continuous
    power_ramping_time_us: 0
    dl_buffer_size_policy: auto
ru_dummy:
  dl_processing_delay: 1
  time_scaling: 1
fapi:
  l2_nof_slots_ahead: 0
hal:
  eal_args: null
  bbdev_hwacc:
    bbdev_acc_type: srs
    hwacc_type: null
    id: 0
    msg_mbuf_size: null
    rm_mbuf_size: null
    nof_mbuf: null
    pdsch_enc:
      nof_hwacc: 0
      cb_mode: false
      max_buffer_size: null
      dedicated_queue: true
    pusch_dec:
      nof_hwacc: 0
      ext_softbuffer: true
      harq_context_size: null
      dedicated_queue: true
buffer_pool:
  nof_segments: 1048576
  segment_size: 2048
expert_phy:
  max_proc_delay: 5
  pusch_dec_max_iterations: 6
  pusch_dec_enable_early_stop: true
  pusch_sinr_calc_method: post_equalization
  max_request_headroom_slots: 0
expert_execution:
  cell_affinities:
  - l1_dl_cpus: null
    l1_ul_cpus: null
    l1_dl_pinning: null
    l1_ul_pinning: null
    l2_cell_cpus: null
    l2_cell_pinning: null
    ru_cpus: null
    ru_pinning: null
  affinities:
    isolated_cpus: null
    low_priority_cpus: null
    low_priority_pinning: null
    ru_timing_cpu: null
    ofh: null
  threads:
    non_rt:
      nof_non_rt_threads: 4
    upper_phy:
      pdsch_processor_type: auto
      nof_pusch_decoder_threads: 1
      nof_ul_threads: 1
      nof_dl_threads: 4
    lower_phy:
      execution_profile: quad
    ofh:
      enable_dl_parallelization: true
test_mode:
  enable: false
  integrity_enable: false
  ciphering_enable: false
  nea_algo: 2
  nia_algo: 2
  test_ue:
    rnti: 0
    nof_ues: 1
    auto_ack_indication_delay: null
    pdsch_active: true
    pusch_active: true
    cqi: 15
    pmi: 0
    ri: 1
    i_1_1: 0
    i_1_3: 0
    i_2: 0
log:
  filename: null
  all_level: warning
  lib_level: warning
  e2ap_level: warning
  config_level: none
  tracing_filename: null
  rrc_level: warning
  ngap_level: warning
  sec_level: warning
  pdcp_level: warning
  sdap_level: warning
  cu_level: warning
  mac_level: warning
  rlc_level: warning
  f1ap_level: warning
  f1u_level: warning
  gtpu_level: warning
  du_level: warning
  metrics_level: none
  f1ap_json_enabled: false
  hal_level: warning
  broadcast_enabled: false
  phy_rx_symbols_filename: null
  phy_rx_symbols_port: 0
  phy_rx_symbols_prach: false
  hex_max_size: 0
  fapi_level: warning
  ofh_level: warning
  radio_level: info
  phy_level: warning
pcap:
  ngap_filename: /tmp/gnb_ngap.pcap
  ngap_enable: false
  n3_filename: /tmp/gnb_n3.pcap
  n3_enable: false
  e1ap_filename: /tmp/gnb_e1ap.pcap
  e1ap_enable: false
  e2ap_filename: /tmp/gnb_e2ap.pcap
  e2ap_enable: false
  f1ap_filename: /tmp/gnb_f1ap.pcap
  f1ap_enable: false
  f1u_filename: /tmp/gnb_f1u.pcap
  f1u_enable: false
  rlc_filename: /tmp/gnb_rlc.pcap
  rlc_rb_type: all
  rlc_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  mac_type: udp
  mac_enable: false
metrics:
  addr: 127.0.0.1
  port: 55555
  cu_cp_statistics_report_period: 1
  cu_up_statistics_report_period: 1
  pdcp_report_period: 0
  rlc_report_period: 1000
  rlc_json_enable: false
  enable_json_metrics: false
  autostart_stdout_metrics: false
  stdout_metrics_period: null
